---
title: "MakeoverMonday 2019/34 - Smart Phone Use"
author: "Cedric Scherer"
date: "18th of August 2019"
output:
  html_document:
    theme: paper
    highlight: kate
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE)
```

```{r prep, message=FALSE}
## packages
library(tidyverse)
library(ggtext)
library(showtext)
library(patchwork)

font_add_google("Roboto Mono", "Roboto Mono")
font_add_google("Oswald", "Oswald")
showtext_auto()
```


```{r data}
df <- tibble(
  question = c(0.2, 0.2, 1.7, 1.7, 1.7, 1.7, 2.9, 2.9, 2.9, 2.9, 4.1, 4.1, 4.1, 4.1),
  percent = c(54, 36, 44, 28, 26, 32, 14, 37, 30, 42, 8, 23, 15, 24),
  percent_cum = c(54, 36, 44, 72, 26, 58, 14, 51, 30, 72, 8, 31, 15, 39),
  group = as.factor(c("Teens", "Parents", rep(c("Teens", "Teens", "Parents", "Parents"), 3))),
  answer = as.factor(c(0, 0, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2)) # 0 = yes, 1 = often, 2 = sometimes
)
```


```{r plot}
bars <- ggplot(df, aes(question, percent, fill = group)) + 
  geom_col(data = filter(df, answer == 0), aes(question, percent, fill = group), 
           position = position_dodge(width = 0.9), width = 0.8) +
  geom_col(data = filter(df, answer == 1), aes(question, percent, fill = group), 
           position = position_dodge(width = 0.9), width = 0.8, alpha = 0.4) +
  geom_col(data = df %>% 
             filter(answer %in% c(1, 2)) %>% 
             group_by(question, group) %>% 
             summarize(percent = sum(percent)), aes(question, percent, fill = group), 
           position = position_dodge(width = 0.9), width = 0.8, alpha = 0.55) +
  geom_text(data = df %>% 
              filter(answer %in% c(1, 2)) %>% 
              mutate(percent = glue::glue("{percent}%")), 
            aes(question, percent_cum - 3, label = percent, group = group),
            position = position_dodge(width = 0.9), color = "white", 
            fontface = "bold", size = 3, family = "Roboto Mono") +
  geom_text(data = df %>% 
              group_by(question, group) %>% 
              summarize(percent = sum(percent)) %>% 
              mutate(percent = glue::glue("{percent}%")), 
            aes(question, -3.8, label = percent, group = group, color = group),
            position = position_dodge(width = 0.9), size = 4.5, fontface = "bold") +
  annotate("text", x = 1.47, y = 20, label = "Often", color = "white", 
           fontface = "bold", family = "Oswald", size = 3.5) +
  annotate("text", x = 1.47, y = 56, label = "Sometimes", color = "white", 
           fontface = "bold", family = "Oswald", size = 3.5) +
  scale_fill_manual(values = c("#0048cc", "#ff9000"), guide = F) +
  scale_color_manual(values = c("#0048cc", "#ff9000"), guide = F) +
  scale_x_reverse(breaks = c(0.2, 1.7, 2.9, 4.1), 
                  labels = c("... spend too much time\non their cellphone",
                             "... check phone for messages\nas soon as they wake up",
                             "... feel their parent/teen is distracted\nby their phone while having\nin-person conversations",
                             "... lose focus in class/work because\nthey are checking their cellphone")) +
  coord_flip() +
  labs(x = NULL, y = NULL,
       caption = 'Source: "How Parents and Teens Navigate Screen Time and Device Distraction" by Pew Research Center  \nSurvey conducted March 7-April 10, 2018, with 1058 parents of teens and 743 teens (teens are between 13 and 17 years old)  \n\nVisualization by Cédric Scherer  ') +
  theme(rect = element_blank(),
        line = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size = 14, color = "grey50", family = "Oswald"),
        plot.caption = element_text(size = 9, color = "grey50", family = "Oswald"))
```

```{r title}
## left-alligned title
title <- ggplot(data.frame(x = 1:2, y = 1:10)) +
  labs(x = NULL, y = NULL,
       title = "Parents and teens report varying levels of attachment\nand distraction due to their cellphones",
       subtitle = "Percent of U.S. <span style='color:#ff9000'>**teens**</span> and <span style='color:#0048cc'>**parents**</span> who say they...") +
  theme(line = element_blank(),
        plot.background = element_rect(fill = "transparent", color = "transparent"),
        panel.background = element_rect(fill = "transparent"),
        panel.border = element_rect(color = "transparent"),
        axis.text = element_blank(),
        plot.title = element_text(size = 27, family = "Oswald", face = "bold", margin = margin(b = 15)),
        plot.subtitle = element_markdown(size = 17, family = "Oswald", color = "grey50"))
```

```{r full-panel, fig.width = 8.5, fig.height = 6.2}
title + bars + plot_layout(widths = c(0.02, 1))

ggsave(here::here("plots", "2019_34_phone-use.pdf"), width = 8.5, height = 6.2, device = cairo_pdf)
```

***

```{r session}
sessionInfo()
```